#### Phase-1 #####

In [100]:
# Import libraries:
import numpy as np 
import pandas as pd # It handling tables,reading file.
import matplotlib.pyplot as plt

In [101]:
# read .csv file:
data = pd.read_csv('Salary_Data.csv')
data

,YearsExperience,Salary
0,1.1,39343.0
1,1.3,46205.0
2,1.5,37731.0
3,2.0,43525.0
4,2.2,39891.0
5,2.9,56642.0
6,3.0,60150.0
7,3.2,54445.0
8,3.2,64445.0
9,3.7,57189.0


In [102]:
# Split input and output:
independent = data[['YearsExperience']]
dependent = data[['Salary']]

In [103]:
# split dataset for training and testing:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [104]:
# Learning process:
from sklearn.linear_model import LinearRegression# import linearRegression
regressor = LinearRegression()#it assign in the name of regressor
#train the model:
regressor.fit(x_train,y_train)# here learning or training is happen

LinearRegression()

In [105]:
# linear formula is y = wx+b
# w(weight/slope)
# bias

In [106]:
weight=regressor.coef_
weight

array([[9360.26128619]])

In [107]:
bias=regressor.intercept_
bias

array([26777.3913412])

In [108]:
# Test or predict:
y_pred=regressor.predict(x_test)
y_pred

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [109]:
# Evaluation metrics:
# r2 score only 0 to 1... r2 is nearly 1 means it is a good model:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)# r2 = actual value/predicted value
r_score

0.9740993407213511

In [110]:
# 0.9 nearly one so, it's a very good model

In [111]:
# Save the model:
filename = 'finalized_model_linear.sav'# assigning the file name

In [112]:
import pickle
pickle.dump(regressor,open(filename,'wb'))
# dump(write) the model in that particular named file.

In [113]:
# load the model for final check:
loaded_model=pickle.load(open('finalized_model_linear.sav','rb'))
loaded_model

LinearRegression()

In [114]:
#Final check:
result=loaded_model.predict([[13]])#prediction
result

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[148460.78806172]])